/*
 * SERVICIOS PROYECTO
 *
 * API del PROYECTO
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Swashbuckle.AspNetCore.Annotations;
using Swashbuckle.AspNetCore.SwaggerGen;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;
using IO.Swagger.Attributes;

using Microsoft.AspNetCore.Authorization;
using IO.Swagger.Models;

namespace IO.Swagger.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public class BILLETEApiController : ControllerBase
    { 
        /// <summary>
        /// Obtiene el billete con mejor puntuación
        /// </summary>
        /// <param name="billetes">pasar lista de billetes</param>
        /// <response code="200">Billete con mejor puntuación</response>
        /// <response code="400">No hay ningún billete</response>
        [HttpGet]
        [Route("/aditwitter20212022/proyecto/1.0.0/billetes")]
        [ValidateModelState]
        [SwaggerOperation("BilletesGet")]
        [SwaggerResponse(statusCode: 200, type: typeof(Billete), description: "Billete con mejor puntuación")]
        public virtual IActionResult BilletesGet([FromQuery][Required()]Billete billetes)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default(Billete));

            //TODO: Uncomment the next line to return response 400 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(400);
            string exampleJson = null;
            exampleJson = "{\n  \"precio\" : 129.96,\n  \"numeroPersonas\" : 2,\n  \"disponibilidad\" : true,\n  \"lugar\" : \"Mallorca\",\n  \"name\" : \"Vueling\",\n  \"description\" : \"Billete a Mallorca\",\n  \"id\" : 1\n}";
            
                        var example = exampleJson != null
                        ? JsonConvert.DeserializeObject<Billete>(exampleJson)
                        : default(Billete);            //TODO: Change the data returned
            return new ObjectResult(example);
        }

        /// <summary>
        /// Comprobar billetes disponibles
        /// </summary>
        /// <param name="listaBilletes">Lista de billetes que cumplen las características anteriores</param>
        /// <response code="200">Billetes con las características</response>
        /// <response code="400">ERROR 400: No hay billetes con esas características</response>
        [HttpPost]
        [Route("/aditwitter20212022/proyecto/1.0.0/comprobarDisponibilidadBillete")]
        [ValidateModelState]
        [SwaggerOperation("ComprobarDisponibilidadBilletePost")]
        [SwaggerResponse(statusCode: 200, type: typeof(List<Billete>), description: "Billetes con las características")]
        public virtual IActionResult ComprobarDisponibilidadBilletePost([FromQuery][Required()]List<Billete> listaBilletes)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default(List<Billete>));

            //TODO: Uncomment the next line to return response 400 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(400);
            string exampleJson = null;
            exampleJson = "[ {\n  \"precio\" : 129.96,\n  \"numeroPersonas\" : 2,\n  \"disponibilidad\" : true,\n  \"lugar\" : \"Mallorca\",\n  \"name\" : \"Vueling\",\n  \"description\" : \"Billete a Mallorca\",\n  \"id\" : 1\n}, {\n  \"precio\" : 129.96,\n  \"numeroPersonas\" : 2,\n  \"disponibilidad\" : true,\n  \"lugar\" : \"Mallorca\",\n  \"name\" : \"Vueling\",\n  \"description\" : \"Billete a Mallorca\",\n  \"id\" : 1\n} ]";
            
                        var example = exampleJson != null
                        ? JsonConvert.DeserializeObject<List<Billete>>(exampleJson)
                        : default(List<Billete>);            //TODO: Change the data returned
            return new ObjectResult(example);
        }

        /// <summary>
        /// Comprobar billetes para esas caracterísiticas
        /// </summary>
        /// <param name="fechaIn">Check-in con formato YYYY-MM-DD</param>
        /// <param name="fechaOut">Check-out con formato YYYY-MM-DD</param>
        /// <param name="lugarIn">pasar lugar origen de la estancia</param>
        /// <param name="lugarOut">pasar lugar destino de la estancia</param>
        /// <response code="200">Billetes con las características</response>
        /// <response code="400">ERROR 400: No hay billetes con esas características</response>
        [HttpPost]
        [Route("/aditwitter20212022/proyecto/1.0.0/comprobarFechaLugarBillete/{fechaIn}/{fechaOut}/{lugarIn}/{lugarOut}")]
        [ValidateModelState]
        [SwaggerOperation("ComprobarFechaLugarBilleteFechaInFechaOutLugarInLugarOutPost")]
        [SwaggerResponse(statusCode: 200, type: typeof(List<Billete>), description: "Billetes con las características")]
        public virtual IActionResult ComprobarFechaLugarBilleteFechaInFechaOutLugarInLugarOutPost([FromRoute][Required]string fechaIn, [FromRoute][Required]string fechaOut, [FromRoute][Required]string lugarIn, [FromRoute][Required]string lugarOut)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default(List<Billete>));

            //TODO: Uncomment the next line to return response 400 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(400);
            string exampleJson = null;
            exampleJson = "[ {\n  \"precio\" : 129.96,\n  \"numeroPersonas\" : 2,\n  \"disponibilidad\" : true,\n  \"lugar\" : \"Mallorca\",\n  \"name\" : \"Vueling\",\n  \"description\" : \"Billete a Mallorca\",\n  \"id\" : 1\n}, {\n  \"precio\" : 129.96,\n  \"numeroPersonas\" : 2,\n  \"disponibilidad\" : true,\n  \"lugar\" : \"Mallorca\",\n  \"name\" : \"Vueling\",\n  \"description\" : \"Billete a Mallorca\",\n  \"id\" : 1\n} ]";
            
                        var example = exampleJson != null
                        ? JsonConvert.DeserializeObject<List<Billete>>(exampleJson)
                        : default(List<Billete>);            //TODO: Change the data returned
            return new ObjectResult(example);
        }

        /// <summary>
        /// Comprobar billetes para esas caracterísiticas
        /// </summary>
        /// <param name="n">Número de personas</param>
        /// <param name="listaBilletes">Lista de bileltes que cumplen las características anteriores</param>
        /// <response code="200">Billetes con las características</response>
        /// <response code="400">ERROR 400: No hay billetes con esas características</response>
        [HttpPost]
        [Route("/aditwitter20212022/proyecto/1.0.0/comprobarPersonasBillete/{n}")]
        [ValidateModelState]
        [SwaggerOperation("ComprobarPersonasBilleteNPost")]
        [SwaggerResponse(statusCode: 200, type: typeof(List<Billete>), description: "Billetes con las características")]
        public virtual IActionResult ComprobarPersonasBilleteNPost([FromRoute][Required]int? n, [FromQuery][Required()]List<Billete> listaBilletes)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default(List<Billete>));

            //TODO: Uncomment the next line to return response 400 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(400);
            string exampleJson = null;
            exampleJson = "[ {\n  \"precio\" : 129.96,\n  \"numeroPersonas\" : 2,\n  \"disponibilidad\" : true,\n  \"lugar\" : \"Mallorca\",\n  \"name\" : \"Vueling\",\n  \"description\" : \"Billete a Mallorca\",\n  \"id\" : 1\n}, {\n  \"precio\" : 129.96,\n  \"numeroPersonas\" : 2,\n  \"disponibilidad\" : true,\n  \"lugar\" : \"Mallorca\",\n  \"name\" : \"Vueling\",\n  \"description\" : \"Billete a Mallorca\",\n  \"id\" : 1\n} ]";
            
                        var example = exampleJson != null
                        ? JsonConvert.DeserializeObject<List<Billete>>(exampleJson)
                        : default(List<Billete>);            //TODO: Change the data returned
            return new ObjectResult(example);
        }

        /// <summary>
        /// Comprobar billetes para esas caracterísiticas
        /// </summary>
        /// <param name="precioInicio">Rango inicial del precio</param>
        /// <param name="precioFin">Rango final del precio</param>
        /// <param name="listaBilletes">Lista de billetes que cumplen las características anteriores</param>
        /// <response code="200">Billetes con las características</response>
        /// <response code="400">ERROR 400: No hay billetes con esas características</response>
        [HttpPost]
        [Route("/aditwitter20212022/proyecto/1.0.0/comprobarPreciosBillete/{precioInicio}/{precioFin}")]
        [ValidateModelState]
        [SwaggerOperation("ComprobarPreciosBilletePrecioInicioPrecioFinPost")]
        [SwaggerResponse(statusCode: 200, type: typeof(List<Billete>), description: "Billetes con las características")]
        public virtual IActionResult ComprobarPreciosBilletePrecioInicioPrecioFinPost([FromRoute][Required]decimal? precioInicio, [FromRoute][Required]decimal? precioFin, [FromQuery][Required()]List<Billete> listaBilletes)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default(List<Billete>));

            //TODO: Uncomment the next line to return response 400 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(400);
            string exampleJson = null;
            exampleJson = "[ {\n  \"precio\" : 129.96,\n  \"numeroPersonas\" : 2,\n  \"disponibilidad\" : true,\n  \"lugar\" : \"Mallorca\",\n  \"name\" : \"Vueling\",\n  \"description\" : \"Billete a Mallorca\",\n  \"id\" : 1\n}, {\n  \"precio\" : 129.96,\n  \"numeroPersonas\" : 2,\n  \"disponibilidad\" : true,\n  \"lugar\" : \"Mallorca\",\n  \"name\" : \"Vueling\",\n  \"description\" : \"Billete a Mallorca\",\n  \"id\" : 1\n} ]";
            
                        var example = exampleJson != null
                        ? JsonConvert.DeserializeObject<List<Billete>>(exampleJson)
                        : default(List<Billete>);            //TODO: Change the data returned
            return new ObjectResult(example);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>Eliminar reserva</remarks>
        /// <param name="id">pasar id de la reserva a borrar</param>
        /// <response code="204">Reserva borrada</response>
        /// <response code="404">No se ha encontrado la reserva</response>
        [HttpDelete]
        [Route("/aditwitter20212022/proyecto/1.0.0/reserva/billetes/borrar/{id}")]
        [ValidateModelState]
        [SwaggerOperation("ReservaBilletesBorrarIdDelete")]
        [SwaggerResponse(statusCode: 404, type: typeof(InlineResponse404), description: "No se ha encontrado la reserva")]
        public virtual IActionResult ReservaBilletesBorrarIdDelete([FromRoute][Required]int? id)
        { 
            //TODO: Uncomment the next line to return response 204 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(204);

            //TODO: Uncomment the next line to return response 404 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(404, default(InlineResponse404));

            throw new NotImplementedException();
        }

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>Ver detalles de la reserva</remarks>
        /// <param name="id">pasar id de la reserva del billete</param>
        /// <response code="200">Reserva del billete se devuelve</response>
        /// <response code="400">No existe la reserva del billete</response>
        [HttpGet]
        [Route("/aditwitter20212022/proyecto/1.0.0/reserva/billetes/consultar/{id}")]
        [ValidateModelState]
        [SwaggerOperation("ReservaBilletesConsultarIdGet")]
        [SwaggerResponse(statusCode: 200, type: typeof(ReservaBillete), description: "Reserva del billete se devuelve")]
        [SwaggerResponse(statusCode: 400, type: typeof(InlineResponse4001), description: "No existe la reserva del billete")]
        public virtual IActionResult ReservaBilletesConsultarIdGet([FromRoute][Required]int? id)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default(ReservaBillete));

            //TODO: Uncomment the next line to return response 400 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(400, default(InlineResponse4001));
            string exampleJson = null;
            exampleJson = "{\n  \"fechaInicio\" : \"fechaInicio\",\n  \"codigoBillete\" : \"codigoBillete\",\n  \"dniCliente\" : \"dniCliente\",\n  \"precioTotal\" : 6.027456183070403,\n  \"fechaFin\" : \"fechaFin\",\n  \"idReserva\" : 0\n}";
            
                        var example = exampleJson != null
                        ? JsonConvert.DeserializeObject<ReservaBillete>(exampleJson)
                        : default(ReservaBillete);            //TODO: Change the data returned
            return new ObjectResult(example);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>Decrementar precio de la reserva del billete</remarks>
        /// <param name="id">pasar id de la reserva</param>
        /// <param name="body">Reserva del billete</param>
        /// <response code="201">Billete modificado</response>
        /// <response code="404">Billete no encontrado</response>
        [HttpPut]
        [Route("/aditwitter20212022/proyecto/1.0.0/reserva/billetes/modificar/{id}")]
        [ValidateModelState]
        [SwaggerOperation("ReservaBilletesModificarIdPut")]
        public virtual IActionResult ReservaBilletesModificarIdPut([FromRoute][Required]int? id, [FromBody]ReservaBillete body)
        { 
            //TODO: Uncomment the next line to return response 201 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(201);

            //TODO: Uncomment the next line to return response 404 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(404);

            throw new NotImplementedException();
        }

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>Crear una reserva del billete</remarks>
        /// <param name="idBillete">pasar el id del mejor billete</param>
        /// <param name="body">Reserva de Billete</param>
        /// <response code="201">Reserva del billete creada</response>
        /// <response code="400">No existe ese billete</response>
        /// <response code="409">Esa reserva ya existe</response>
        [HttpPost]
        [Route("/aditwitter20212022/proyecto/1.0.0/reserva/billetes/nuevo")]
        [ValidateModelState]
        [SwaggerOperation("ReservaBilletesNuevoPost")]
        [SwaggerResponse(statusCode: 400, type: typeof(InlineResponse400), description: "No existe ese billete")]
        [SwaggerResponse(statusCode: 409, type: typeof(InlineResponse409), description: "Esa reserva ya existe")]
        public virtual IActionResult ReservaBilletesNuevoPost([FromQuery][Required()]int? idBillete, [FromBody]ReservaBillete body)
        { 
            //TODO: Uncomment the next line to return response 201 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(201);

            //TODO: Uncomment the next line to return response 400 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(400, default(InlineResponse400));

            //TODO: Uncomment the next line to return response 409 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(409, default(InlineResponse409));

            throw new NotImplementedException();
        }
    }
}
