/*
 * Hotel
 *
 * API del HOTEL
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Swashbuckle.AspNetCore.Annotations;
using Swashbuckle.AspNetCore.SwaggerGen;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;
using IO.Swagger.Attributes;

using Microsoft.AspNetCore.Authorization;
using IO.Swagger.Models;

namespace IO.Swagger.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public class DefaultApiController : ControllerBase
    { 
        /// <summary>
        /// Obtiene el listado de todos los hoteles
        /// </summary>
        /// <response code="200">Muestra el listado de todos los hoteles</response>
        /// <response code="400">No hay ningún hotel</response>
        [HttpGet]
        [Route("/aditwitter20212022/Hotel/1.0.0/hoteles")]
        [ValidateModelState]
        [SwaggerOperation("HotelesGet")]
        [SwaggerResponse(statusCode: 200, type: typeof(Hotel), description: "Muestra el mejor Hotel")]
        public virtual IActionResult HoteleGet([FromBody][Required()] List<Hotel> listaHoteles)
        { 

            Hotel mejorHotel = new Hotel();
            string disp = "";
            string exampleJson = "";
            for (int i = 0; i < listaHoteles.Count; i++)
            {
                if(listaHoteles[i].Puntuacion > mejorHotel.Puntuacion)
                {
                    mejorHotel = listaHoteles[i];
                }
            }
            if (mejorHotel.Disponibilidad.Value)
            {
                disp = "true";
            }
            else
            {
                disp = "false";
            }
            exampleJson = "{\n  \"numeroPersonas\" : " + mejorHotel.NumeroPersonas.ToString() + ",\n  \"disponibilidad\" : " + disp + ",\n  \"puntuacion\" : " + mejorHotel.Puntuacion.ToString() + ",\n  \"precioNoche\" : " + mejorHotel.PrecioNoche.ToString() + ",\n  \"lugar\" : \"" + mejorHotel.Lugar + "\",\n  \"name\" : \"" + mejorHotel.NumeroPersonas + "\",\n  \"description\" : \"" + mejorHotel.NumeroPersonas.ToString() + "\",\n  \"id\" : " + mejorHotel.Id.ToString() + " \n}";
           
            var example = exampleJson != null
            ? JsonConvert.DeserializeObject<Hotel>(exampleJson)
            : default(Hotel);            //TODO: Change the data returned
            return new ObjectResult(example);
        }

    }
}
